matrix:
  include:
    - language: node_js
      node_js: '12'
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "QebcPbKl5ddMatMZWqV7cMFhHUzO1ubWuA5yMGlK6+W58p8YuC44lasYk4YlnXRSSfmNTV0ExzjXPiSj3w7ytbpFu5Syapy2BTCp4LYZGoMQJWvzj5lKPpNNGb0peuRRFooRa0Cw4Bl6FU0iMEVJwkNGc6Kx9MqLxUJ2zsGqLOXQlFV0n5YJcf/afE5c8leyFnlO20nz3RlojUJ0tVpN0GYAq1pRAmucLOmdvk2qGoPx4zrzkoNkdrH2XwMa3GwUMDEXStvgTbHPiI5oJMHlgNbxxD6g2nAucc04Ifc12FPumqjOZ9hEwYlD4ZoOQX6VQEW8Uclk1zsNfQOAMA2Pheeqw4VwORueYtTE6hcdPWBRPekKq/yANSeRkuGrQbBRzFY6D/820YqnEqV4+5cDqcrZ528qWaA9kJfT5CBf1nNogBQfvN+BCFmMvX7SHf9OHdGmj59KBSRniOimpWLWiKIzYLvORZIjVdHZllHszbXlrn5w6nuKg9JjqBVnQiZixrEMLNLg8iy3TOCkEpLYwrng1JCEyuba74cz1R48LpP+RzBNvRbYlPPtpp5JNwy5+1+8+pwBmwURLbAyyAJzzZ6NVWjlkhsxjlVJ0YqRFCRaGucgyLpEJJ6wZghXX1JyJ4PpC/T0vfTBdqdAH1exrlWZRjGcycYMR2a1LsO6oQ8="
      cache:
        - yarn: true
      before_install:
        - cd frontend
      install:
        - yarn install
      script:
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
        - cd ..
        - sonar-scanner

    - language: python
      python: '3.7.5'
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "QebcPbKl5ddMatMZWqV7cMFhHUzO1ubWuA5yMGlK6+W58p8YuC44lasYk4YlnXRSSfmNTV0ExzjXPiSj3w7ytbpFu5Syapy2BTCp4LYZGoMQJWvzj5lKPpNNGb0peuRRFooRa0Cw4Bl6FU0iMEVJwkNGc6Kx9MqLxUJ2zsGqLOXQlFV0n5YJcf/afE5c8leyFnlO20nz3RlojUJ0tVpN0GYAq1pRAmucLOmdvk2qGoPx4zrzkoNkdrH2XwMa3GwUMDEXStvgTbHPiI5oJMHlgNbxxD6g2nAucc04Ifc12FPumqjOZ9hEwYlD4ZoOQX6VQEW8Uclk1zsNfQOAMA2Pheeqw4VwORueYtTE6hcdPWBRPekKq/yANSeRkuGrQbBRzFY6D/820YqnEqV4+5cDqcrZ528qWaA9kJfT5CBf1nNogBQfvN+BCFmMvX7SHf9OHdGmj59KBSRniOimpWLWiKIzYLvORZIjVdHZllHszbXlrn5w6nuKg9JjqBVnQiZixrEMLNLg8iy3TOCkEpLYwrng1JCEyuba74cz1R48LpP+RzBNvRbYlPPtpp5JNwy5+1+8+pwBmwURLbAyyAJzzZ6NVWjlkhsxjlVJ0YqRFCRaGucgyLpEJJ6wZghXX1JyJ4PpC/T0vfTBdqdAH1exrlWZRjGcycYMR2a1LsO6oQ8="
      cache:
        - pip: true
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
        - cd ..
        - sonar-scanner
