matrix:
  include:
    - language: node_js
      node_js: '12'
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "iooqA1OqhmHxy7TO8T9mZ9Jputj4LmgDBlVPwDeCkbz6T0QJjpH3WVH0cKO05PBYE4cnBnufExsw3FwcAY07d7pnQvlbIDYwkKRtuGafIB0jQJjZTvt5nBibIaWFSB4egcRWVi9alrtoqUruaCbT+Oqcu+MfL/Tex5B41iUn0F8yKHvwGCRpGnATvsCIxIgyFePMQUie2YiwlewlSfmznXxIIRSgmOBEw3yaytMNClCiHCgdWzs+33SiAL7bIl37I9/837SBR/0sJ8/eE2KYed7nok6DMPPmgTqa/TriOt21BodbrSxWUW2K0NsHJsgk7WzpF93ix9OU1FCVuQ9UHkqtpit2wHDu1QnwmoCJFbOxqSmmBRyHZmbMZ0OGoSmGqfx9nuypJP67VHYyXZkZU4b2qe6bcO2T22BT3WLT9BU61qGczsTIzjGhBCbX07Ph73aK5zBkBYzyKKUKI8JYmR4S6Gh4f1+mPxQjwV8ViD2GhScxBYo8ATlAJ5/MKqBCQQzPNgvzla/BRYjWT63vtvj2fOsysXc+Ub2UUCpq+yWiSOgtEdINSex23M//ZPRNQhkocOng1pefL5hogfZwPmd+6eVuq/PgRxlZNHzUXW/bhf4uznCSCKRFHwOVZFYwcWl6rufzxzTzJ8y0HmDHG9LeNZClb9ftaWZpTsJfSOk="
      cache:
        - yarn: true
      before_install:
        - cd frontend
      install:
        - yarn install
      script:
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
        - cd .. && sonar-scanner

    - language: python
      python: '3.7.5'
      cache:
        - pip: true
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
