# Generated by Django 3.1.2 on 2020-11-04 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_content', models.TextField(blank=True, default='')),
                ('phrase_key_word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_phrase', models.ManyToManyField(blank=True, through='wordlist.AddPhrase', to='wordlist.Phrase')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='addphrase',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordlist.phrase'),
        ),
        migrations.AddField(
            model_name='addphrase',
            name='wordlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordlist.wordlist'),
        ),
    ]
