# Generated by Django 3.1.2 on 2020-11-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrase',
            old_name='phrase_key_word',
            new_name='phrase_keyword',
        ),
    ]
