# Generated by Django 3.1.2 on 2020-11-05 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordlist', '0002_auto_20201104_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlist',
            name='learner',
        ),
        migrations.AddField(
            model_name='wordlist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
