# Generated by Django 3.1.2 on 2020-11-10 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testhistory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='testhistory',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
